### ISSUE TITLE
the log file

### ISSUE THREAD

**Issue by zwy1996** [won-bae/rethinkingCAM#1]
Hi, nice work!

When I use the "bash scripts/setup.sh --data_setup", I met the following error,
ImportError: cannot import name 'log'

I think maybe lack of the log file
Thank you very much!

**Comment by won-bae** [comment]
Hi, thanks for the feedback!
Just fixed the bug.

**Comment by zwy1996** [comment]
Thanks for you response to me in time.

And I used the instructions "bash scripts/run_train.sh --config_path configs/vgg16_tap.yml --tag vgg16_tap --train_dir /path/to/train/dir",  I met the following questions.
1. Is the code have no gpu version?,That maybe slowly, ([2021-02-22 09:42:31,335 - out] GPU is not available.)
2. Is the code have no pre-trained model? ([2021-02-22 09:42:32,379 - out] No checkpoint found. Initializing model from scratch.)

Thank you very much!

**Comment by zwy1996** [comment]
Hi,
I fixed the questions, 
Thanks very  much!
